import { useEffect, useMemo, useState } from 'react'
import {
  Alert,
  Box,
  Button,
  Stack,
  Switch,
  TextField,
  FormControlLabel,
  MenuItem,
  Select,
  InputLabel,
  FormControl,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  List,
  ListItemButton,
  ListItemText,
  Typography
} from '@mui/material'
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome'
import MonitorHeartIcon from '@mui/icons-material/MonitorHeart'
import SyncIcon from '@mui/icons-material/Sync'
import LightbulbIcon from '@mui/icons-material/Lightbulb'
import type { FingerprintConfig, ProfileData } from '@shared/types'
import { SectionCard } from '../SectionCard'
import { AutoGenerateDialog } from '../AutoGenerateDialog'
import { useToast } from '../../hooks/useToasts'

interface Props {
  profile: ProfileData
  setProfile: (patch: Partial<ProfileData>) => void
}

/** Binds one fingerprint field to the draft. */
function Fp<T extends keyof FingerprintConfig>({
  label,
  fp,
  field,
  onChange,
  type = 'text',
  fullWidth = true
}: {
  label: string
  fp: FingerprintConfig
  field: T
  onChange: (patch: Partial<FingerprintConfig>) => void
  type?: string
  fullWidth?: boolean
}): React.JSX.Element {
  return (
    <TextField
      label={label}
      type={type}
      size="small"
      fullWidth={fullWidth}
      value={String(fp[field])}
      onChange={(e) => {
        const raw = e.target.value
        const value = type === 'number' ? Number(raw) : raw
        onChange({ [field]: value } as Partial<FingerprintConfig>)
      }}
    />
  )
}

/** The Fingerprint editor tab. */
export function FingerprintTab({ profile, setProfile }: Props): React.JSX.Element {
  const toast = useToast()
  const fp = profile.fingerprint
  const setFp = (patch: Partial<FingerprintConfig>): void => setProfile({ fingerprint: { ...fp, ...patch } })
  const [autoOpen, setAutoOpen] = useState(false)
  const [busyReal, setBusyReal] = useState(false)
  const [suggestOpen, setSuggestOpen] = useState(false)
  const [uaList, setUaList] = useState<
    Array<{ ua: string; browser: string; os: string; device: string; platform: string; version: string }>
  >([])
  const [uaFilter, setUaFilter] = useState('all')

  useEffect(() => {
    if (!suggestOpen || uaList.length) return
    void window.stealth.listUserAgents().then(setUaList).catch((e) => toast.error(String(e)))
  }, [suggestOpen, uaList.length, toast])

  const filteredUas = useMemo(() => {
    if (uaFilter === 'all') return uaList
    return uaList.filter((u) => u.browser === uaFilter)
  }, [uaList, uaFilter])

  const realValues = useMemo(() => {
    const nav = navigator as Navigator & { deviceMemory?: number }
    return {
      platform: nav.platform,
      language: nav.language,
      languages: [...(nav.languages ?? [])],
      cores: nav.hardwareConcurrency,
      memory: nav.deviceMemory ?? 4,
      touch: nav.maxTouchPoints,
      width: window.screen.width,
      height: window.screen.height,
      availWidth: window.screen.availWidth,
      availHeight: window.screen.availHeight,
      colorDepth: window.screen.colorDepth,
      dpr: window.devicePixelRatio
    }
  }, [])

  const fillWithReal = async (): Promise<void> => {
    setBusyReal(true)
    try {
      const sys = await window.stealth.getSystemInfo()
      setFp({
        platform: realValues.platform,
        language: realValues.language,
        languages: realValues.languages.length ? realValues.languages : [realValues.language],
        hardwareConcurrency: realValues.cores,
        deviceMemory: Math.max(1, Math.round((sys.totalMemoryGB / 2) / 2) * 2),
        maxTouchPoints: realValues.touch,
        screenWidth: realValues.width,
        screenHeight: realValues.height,
        screenAvailWidth: realValues.availWidth,
        screenAvailHeight: realValues.availHeight,
        screenColorDepth: realValues.colorDepth,
        screenPixelDepth: realValues.colorDepth,
        devicePixelRatio: realValues.dpr
      })
      toast.success('Filled with real system values — tweak them now.')
    } catch (e) {
      toast.error(String(e))
    } finally {
      setBusyReal(false)
    }
  }

  const deriveFromUA = async (): Promise<void> => {
    if (!fp.userAgent.trim()) {
      toast.error('Paste a user-agent string first.')
      return
    }
    try {
      const derived = await window.stealth.deriveFingerprintFromUA(fp.userAgent.trim(), fp.seed)
      setFp(derived)
      toast.success('Values re-derived from this user-agent.')
    } catch (e) {
      toast.error(String(e))
    }
  }

  return (
    <Box>
      {/* Action row */}
      <Stack direction="row" spacing={1.5} sx={{ mb: 2.5, flexWrap: 'wrap' }}>
        <Button variant="contained" startIcon={<AutoAwesomeIcon />} onClick={() => setAutoOpen(true)}>
          Auto-generate realistic fingerprint
        </Button>
        <Button variant="outlined" startIcon={<MonitorHeartIcon />} disabled={busyReal} onClick={() => void fillWithReal()}>
          Fill with real values
        </Button>
        <Button variant="outlined" startIcon={<SyncIcon />} onClick={() => void deriveFromUA()}>
          Re-derive from this UA
        </Button>
      </Stack>

      {/* User-Agent & Platform */}
      <SectionCard title="User-Agent & Platform" subtitle="Controls navigator.userAgent, appVersion, platform, languages">
        <Stack spacing={2}>
          <Stack direction="row" spacing={1} sx={{ alignItems: 'flex-start' }}>
            <TextField
              label="User-Agent"
              size="small"
              fullWidth
              multiline
              minRows={2}
              value={fp.userAgent}
              onChange={(e) => setFp({ userAgent: e.target.value })}
              placeholder="Mozilla/5.0 (Windows NT 10.0; Win64; x64) …"
            />
            <Button
              variant="outlined"
              startIcon={<LightbulbIcon />}
              onClick={() => setSuggestOpen(true)}
              sx={{ whiteSpace: 'nowrap', mt: 0.5 }}
            >
              Suggest
            </Button>
          </Stack>
          <Stack direction="row" spacing={2}>
            <Fp label="Platform" fp={fp} field="platform" onChange={setFp} />
            <Fp label="oscpu (Firefox)" fp={fp} field="oscpu" onChange={setFp} />
          </Stack>
          <Stack direction="row" spacing={2}>
            <Fp label="Language" fp={fp} field="language" onChange={setFp} />
            <TextField
              label="Languages (comma-separated)"
              size="small"
              fullWidth
              value={(fp.languages ?? []).join(', ')}
              onChange={(e) =>
                setFp({
                  languages: e.target.value
                    .split(',')
                    .map((s) => s.trim())
                    .filter(Boolean)
                })
              }
            />
          </Stack>
          <Stack direction="row" spacing={2}>
            <Fp label="Timezone (IANA)" fp={fp} field="timezone" onChange={setFp} />
            <Fp label="TZ offset (min, auto)" fp={fp} field="timezoneOffset" onChange={setFp} type="number" />
          </Stack>
        </Stack>
      </SectionCard>

      {/* Screen */}
      <SectionCard title="Screen" subtitle="Screen size, available area, color depth, pixel ratio">
        <Stack spacing={2}>
          <Stack direction="row" spacing={2}>
            <Fp label="Width" fp={fp} field="screenWidth" onChange={setFp} type="number" />
            <Fp label="Height" fp={fp} field="screenHeight" onChange={setFp} type="number" />
          </Stack>
          <Stack direction="row" spacing={2}>
            <Fp label="Avail width" fp={fp} field="screenAvailWidth" onChange={setFp} type="number" />
            <Fp label="Avail height" fp={fp} field="screenAvailHeight" onChange={setFp} type="number" />
          </Stack>
          <Stack direction="row" spacing={2}>
            <Fp label="Color depth" fp={fp} field="screenColorDepth" onChange={setFp} type="number" />
            <Fp label="Pixel depth" fp={fp} field="screenPixelDepth" onChange={setFp} type="number" />
            <Fp label="devicePixelRatio" fp={fp} field="devicePixelRatio" onChange={setFp} type="number" />
          </Stack>
        </Stack>
      </SectionCard>

      {/* Hardware */}
      <SectionCard title="Hardware" subtitle="CPU cores, RAM and touch support reported to sites">
        <Stack spacing={2}>
          <Stack direction="row" spacing={2}>
            <Fp label="Hardware concurrency" fp={fp} field="hardwareConcurrency" onChange={setFp} type="number" />
            <Fp label="Device memory (GB)" fp={fp} field="deviceMemory" onChange={setFp} type="number" />
            <Fp label="Max touch points" fp={fp} field="maxTouchPoints" onChange={setFp} type="number" />
          </Stack>
        </Stack>
      </SectionCard>

      {/* WebGL */}
      <SectionCard title="WebGL" subtitle="UNMASKED_VENDOR_WEBGL / UNMASKED_RENDERER_WEBGL spoofing">
        <Stack spacing={2}>
          <Fp label="WebGL vendor" fp={fp} field="webglVendor" onChange={setFp} />
          <Fp label="WebGL renderer" fp={fp} field="webglRenderer" onChange={setFp} />
        </Stack>
      </SectionCard>

      {/* Canvas & Audio */}
      <SectionCard title="Canvas & Audio" subtitle="Seeded noise changes hashes but is invisible to the eye/ear">
        <Stack spacing={1.5}>
          <FormControlLabel
            control={<Switch checked={fp.canvasNoiseEnabled} onChange={(e) => setFp({ canvasNoiseEnabled: e.target.checked })} />}
            label="Canvas noise (2D drawing + getImageData)"
          />
          <FormControlLabel
            control={<Switch checked={fp.audioNoiseEnabled} onChange={(e) => setFp({ audioNoiseEnabled: e.target.checked })} />}
            label="Audio noise (AudioBuffer samples)"
          />
          <FormControlLabel
            control={<Switch checked={fp.webRTCLeakProtect} onChange={(e) => setFp({ webRTCLeakProtect: e.target.checked })} />}
            label="WebRTC leak protection (strips ICE candidates)"
          />
          <Stack direction="row" spacing={2}>
            <Fp label="Canvas noise seed" fp={fp} field="canvasNoiseSeed" onChange={setFp} type="number" />
            <Fp label="Audio noise seed" fp={fp} field="audioNoiseSeed" onChange={setFp} type="number" />
          </Stack>
        </Stack>
      </SectionCard>

      {/* Fonts */}
      <SectionCard title="Fonts" subtitle="Only these fonts are enumerable via document.fonts">
        <Stack spacing={1.5}>
          <FormControlLabel
            control={
              <Switch
                checked={fp.fontFingerprintProtection}
                onChange={(e) => setFp({ fontFingerprintProtection: e.target.checked })}
              />
            }
            label="Font fingerprint protection"
          />
          <TextField
            label="Custom fonts (one per line — empty = curated list for the UA's OS)"
            size="small"
            fullWidth
            multiline
            minRows={4}
            value={(fp.customFonts ?? []).join('\n')}
            onChange={(e) =>
              setFp({ customFonts: e.target.value.split('\n').map((s) => s.trim()).filter(Boolean) })
            }
          />
        </Stack>
      </SectionCard>

      {/* Geolocation */}
      <SectionCard title="Geolocation" subtitle="Block or spoof a position">
        <Stack direction="row" spacing={2} sx={{ alignItems: 'center', flexWrap: 'wrap' }}>
          <FormControl size="small" sx={{ minWidth: 180 }}>
            <InputLabel>Mode</InputLabel>
            <Select
              label="Mode"
              value={fp.geolocation.mode}
              onChange={(e) => setFp({ geolocation: { ...fp.geolocation, mode: e.target.value as 'block' | 'spoof' } })}
            >
              <MenuItem value="block">Block (permission denied)</MenuItem>
              <MenuItem value="spoof">Spoof position</MenuItem>
            </Select>
          </FormControl>
          {fp.geolocation.mode === 'spoof' && (
            <>
              <TextField
                label="Latitude"
                type="number"
                size="small"
                value={String(fp.geolocation.latitude)}
                onChange={(e) => setFp({ geolocation: { ...fp.geolocation, latitude: Number(e.target.value) } })}
                sx={{ width: 140 }}
              />
              <TextField
                label="Longitude"
                type="number"
                size="small"
                value={String(fp.geolocation.longitude)}
                onChange={(e) => setFp({ geolocation: { ...fp.geolocation, longitude: Number(e.target.value) } })}
                sx={{ width: 140 }}
              />
            </>
          )}
        </Stack>
      </SectionCard>

      {/* Advanced */}
      <SectionCard title="Advanced" subtitle="Extra toggles for maximum realism">
        <Stack spacing={1.5}>
          <FormControlLabel
            control={<Switch checked={fp.pluginsSpoof} onChange={(e) => setFp({ pluginsSpoof: e.target.checked })} />}
            label="Spoof navigator.plugins / mimeTypes to match the UA family"
          />
          <Alert severity="info" sx={{ borderRadius: 2 }}>
            Seeded RNG: fingerprint.seed = <code>{fp.seed}</code> — the same seed always reproduces the same
            fingerprint. Keep it stable for believable profiles.
          </Alert>
        </Stack>
      </SectionCard>

      <AutoGenerateDialog
        open={autoOpen}
        onClose={() => setAutoOpen(false)}
        onGenerated={(newFp) => {
          setFp(newFp)
          toast.success('Fingerprint generated — auto-saved.')
        }}
      />

      {/* UA Suggest dialog */}
      <Dialog open={suggestOpen} onClose={() => setSuggestOpen(false)} fullWidth maxWidth="md">
        <DialogTitle>Suggest realistic User-Agent</DialogTitle>
        <DialogContent>
          <Stack direction="row" spacing={1} sx={{ mb: 1.5, flexWrap: 'wrap' }}>
            {['all', 'chrome', 'edge', 'brave', 'firefox'].map((b) => (
              <Button
                key={b}
                size="small"
                variant={uaFilter === b ? 'contained' : 'outlined'}
                onClick={() => setUaFilter(b)}
              >
                {b}
              </Button>
            ))}
          </Stack>
          <Typography variant="caption" color="text.secondary" sx={{ mb: 1, display: 'block' }}>
            Pick a real browser UA from the built-in library. Selecting one also re-derives consistent platform /
            screen / GPU values from the same seed.
          </Typography>
          <List dense sx={{ maxHeight: 360, overflow: 'auto', border: '1px solid', borderColor: 'divider', borderRadius: 2 }}>
            {filteredUas.map((entry, i) => (
              <ListItemButton
                key={i}
                onClick={() => {
                  void (async () => {
                    try {
                      const derived = await window.stealth.deriveFingerprintFromUA(entry.ua, fp.seed)
                      setFp(derived)
                      setSuggestOpen(false)
                      toast.success(`Applied ${entry.browser} ${entry.version} (${entry.os}) UA`)
                    } catch (e) {
                      toast.error(String(e))
                    }
                  })()
                }}
              >
                <ListItemText
                  primary={
                    <Typography component="span" sx={{ fontWeight: 600, fontSize: 13 }}>
                      {`${entry.browser} ${entry.version} · ${entry.os} · ${entry.device}`}
                    </Typography>
                  }
                  secondary={
                    <Typography component="span" sx={{ fontSize: 11, wordBreak: 'break-all', display: 'block' }} color="text.secondary">
                      {entry.ua}
                    </Typography>
                  }
                />
              </ListItemButton>
            ))}
            {filteredUas.length === 0 && (
              <Typography variant="body2" color="text.secondary" sx={{ p: 2, textAlign: 'center' }}>
                Loading user-agent library…
              </Typography>
            )}
          </List>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setSuggestOpen(false)}>Close</Button>
        </DialogActions>
      </Dialog>
    </Box>
  )
}
