import { useEffect, useMemo, useState } from 'react'
import {
  Alert,
  Box,
  Button,
  Stack,
  Switch,
  TextField,
  FormControlLabel,
  MenuItem,
  Select,
  InputLabel,
  FormControl,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  List,
  ListItemButton,
  ListItemText,
  Typography
} from '@mui/material'
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome'
import MonitorHeartIcon from '@mui/icons-material/MonitorHeart'
import SyncIcon from '@mui/icons-material/Sync'
import LightbulbIcon from '@mui/icons-material/Lightbulb'
import type { FingerprintConfig, ProfileData } from '@shared/types'
import { SectionCard } from '../SectionCard'
import { AutoGenerateDialog } from '../AutoGenerateDialog'
import { useToast } from '../../hooks/useToasts'

interface Props {
  profile: ProfileData
  setProfile: (patch: Partial<ProfileData>) => void
}

/** Validated number field. */
function FpNum({
  label,
  value,
  onChange,
  min,
  max,
  step,
  fullWidth = true
}: {
  label: string
  value: number
  onChange: (v: number) => void
  min?: number
  max?: number
  step?: number
  fullWidth?: boolean
}): React.JSX.Element {
  const [error, setError] = useState(false)
  return (
    <TextField
      label={label}
      type="number"
      size="small"
      fullWidth={fullWidth}
      value={String(value)}
      error={error}
      onChange={(e) => {
        const n = Number(e.target.value)
        const outOfRange = (min !== undefined && n < min) || (max !== undefined && n > max)
        setError(outOfRange)
        if (!outOfRange) onChange(n)
      }}
      helperText={error ? `${min ?? '...'} – ${max ?? '...'}` : undefined}
      slotProps={step ? { htmlInput: { step } } : undefined}
    />
  )
}

/** Binds one fingerprint text field. */
function Fp<T extends keyof FingerprintConfig>({
  label,
  fp,
  field,
  onChange,
  type = 'text',
  fullWidth = true
}: {
  label: string
  fp: FingerprintConfig
  field: T
  onChange: (patch: Partial<FingerprintConfig>) => void
  type?: string
  fullWidth?: boolean
}): React.JSX.Element {
  return (
    <TextField
      label={label}
      type={type}
      size="small"
      fullWidth={fullWidth}
      value={String(fp[field])}
      onChange={(e) => {
        const raw = e.target.value
        const value = type === 'number' ? Number(raw) : raw
        onChange({ [field]: value } as Partial<FingerprintConfig>)
      }}
    />
  )
}

/** Fingerprint editor tab. */
export function FingerprintTab({ profile, setProfile }: Props): React.JSX.Element {
  const toast = useToast()
  const fp = profile.fingerprint
  const setFp = (patch: Partial<FingerprintConfig>): void => setProfile({ fingerprint: { ...fp, ...patch } })
  const [autoOpen, setAutoOpen] = useState(false)
  const [busyReal, setBusyReal] = useState(false)
  const [suggestOpen, setSuggestOpen] = useState(false)
  const [uaList, setUaList] = useState<
    Array<{ ua: string; browser: string; os: string; device: string; platform: string; version: string }>
  >([])
  const [uaFilter, setUaFilter] = useState('all')

  useEffect(() => {
    if (!suggestOpen || uaList.length) return
    void window.stealth.listUserAgents().then(setUaList).catch((e) => toast.error(String(e)))
  }, [suggestOpen, uaList.length, toast])

  const filteredUas = useMemo(() => {
    if (uaFilter === 'all') return uaList
    return uaList.filter((u) => u.browser === uaFilter)
  }, [uaList, uaFilter])

  const realValues = useMemo(() => {
    const nav = navigator as Navigator & { deviceMemory?: number }
    return {
      platform: nav.platform,
      language: nav.language,
      languages: [...(nav.languages ?? [])],
      cores: nav.hardwareConcurrency,
      memory: nav.deviceMemory ?? 4,
      touch: nav.maxTouchPoints,
      width: window.screen.width,
      height: window.screen.height,
      availWidth: window.screen.availWidth,
      availHeight: window.screen.availHeight,
      colorDepth: window.screen.colorDepth,
      dpr: window.devicePixelRatio
    }
  }, [])

  const fillWithReal = async (): Promise<void> => {
    setBusyReal(true)
    try {
      const sys = await window.stealth.getSystemInfo()
      setFp({
        platform: realValues.platform,
        language: realValues.language,
        languages: realValues.languages.length ? realValues.languages : [realValues.language],
        hardwareConcurrency: realValues.cores,
        deviceMemory: Math.max(1, Math.round((sys.totalMemoryGB / 2) / 2) * 2),
        maxTouchPoints: realValues.touch,
        screenWidth: realValues.width,
        screenHeight: realValues.height,
        screenAvailWidth: realValues.availWidth,
        screenAvailHeight: realValues.availHeight,
        screenColorDepth: realValues.colorDepth,
        screenPixelDepth: realValues.colorDepth,
        devicePixelRatio: realValues.dpr
      })
      toast.success('Filled with real values')
    } catch (e) {
      toast.error(String(e))
    } finally {
      setBusyReal(false)
    }
  }

  const deriveFromUA = async (): Promise<void> => {
    if (!fp.userAgent.trim()) {
      toast.error('Paste a UA first')
      return
    }
    try {
      const derived = await window.stealth.deriveFingerprintFromUA(fp.userAgent.trim(), fp.seed)
      setFp(derived)
      toast.success('Re-derived from UA')
    } catch (e) {
      toast.error(String(e))
    }
  }

  return (
    <Box>
      {/* Action row */}
      <Stack direction="row" spacing={1} sx={{ mb: 2, flexWrap: 'wrap', gap: 1 }}>
        <Button size="small" variant="contained" startIcon={<AutoAwesomeIcon />} onClick={() => setAutoOpen(true)}>
          Auto-generate
        </Button>
        <Button size="small" variant="outlined" startIcon={<MonitorHeartIcon />} disabled={busyReal} onClick={() => void fillWithReal()}>
          Real values
        </Button>
        <Button size="small" variant="outlined" startIcon={<SyncIcon />} onClick={() => void deriveFromUA()}>
          Re-derive
        </Button>
      </Stack>

      {/* User-Agent & Platform */}
      <SectionCard title="User-Agent" subtitle="UA & locale">
        <Stack spacing={1.5}>
          <Stack direction="row" spacing={1} sx={{ alignItems: 'flex-start' }}>
            <TextField
              label="User-Agent"
              size="small"
              fullWidth
              multiline
              minRows={2}
              value={fp.userAgent}
              onChange={(e) => setFp({ userAgent: e.target.value })}
              placeholder="Mozilla/5.0 (Windows NT 10.0; Win64; x64) ..."
            />
            <Button
              size="small"
              variant="outlined"
              startIcon={<LightbulbIcon />}
              onClick={() => setSuggestOpen(true)}
              sx={{ whiteSpace: 'nowrap', mt: 0.5 }}
            >
              Suggest
            </Button>
          </Stack>
          <Stack direction="row" spacing={1.5}>
            <Fp label="Platform" fp={fp} field="platform" onChange={setFp} />
            <Fp label="oscpu" fp={fp} field="oscpu" onChange={setFp} />
          </Stack>
          <Stack direction="row" spacing={1.5}>
            <Fp label="Language" fp={fp} field="language" onChange={setFp} />
            <TextField
              label="Languages (comma-sep)"
              size="small"
              fullWidth
              value={(fp.languages ?? []).join(', ')}
              onChange={(e) =>
                setFp({
                  languages: e.target.value
                    .split(',')
                    .map((s) => s.trim())
                    .filter(Boolean)
                })
              }
            />
          </Stack>
          <Stack direction="row" spacing={1.5}>
            <Fp label="Timezone" fp={fp} field="timezone" onChange={setFp} />
            <Fp label="TZ offset" fp={fp} field="timezoneOffset" onChange={setFp} type="number" />
          </Stack>
        </Stack>
      </SectionCard>

      {/* Screen */}
      <SectionCard title="Screen" subtitle="Resolution & DPR">
        <Stack spacing={1.5}>
          <Stack direction="row" spacing={1.5}>
            <FpNum label="Width" value={fp.screenWidth} onChange={(v) => setFp({ screenWidth: v })} min={320} max={7680} />
            <FpNum label="Height" value={fp.screenHeight} onChange={(v) => setFp({ screenHeight: v })} min={240} max={4320} />
          </Stack>
          <Stack direction="row" spacing={1.5}>
            <FpNum label="Avail W" value={fp.screenAvailWidth} onChange={(v) => setFp({ screenAvailWidth: v })} min={320} max={7680} />
            <FpNum label="Avail H" value={fp.screenAvailHeight} onChange={(v) => setFp({ screenAvailHeight: v })} min={240} max={4320} />
          </Stack>
          <Stack direction="row" spacing={1.5}>
            <FpNum label="Color depth" value={fp.screenColorDepth} onChange={(v) => setFp({ screenColorDepth: v })} min={1} max={48} />
            <FpNum label="Pixel depth" value={fp.screenPixelDepth} onChange={(v) => setFp({ screenPixelDepth: v })} min={1} max={48} />
            <FpNum label="DPR" value={fp.devicePixelRatio} onChange={(v) => setFp({ devicePixelRatio: v })} min={0.25} max={4} step={0.25} />
          </Stack>
        </Stack>
      </SectionCard>

      {/* Hardware */}
      <SectionCard title="Hardware" subtitle="CPU & memory">
        <Stack spacing={1.5}>
          <Stack direction="row" spacing={1.5}>
            <FpNum label="CPU cores" value={fp.hardwareConcurrency} onChange={(v) => setFp({ hardwareConcurrency: v })} min={1} max={128} />
            <FpNum label="Memory (GB)" value={fp.deviceMemory} onChange={(v) => setFp({ deviceMemory: v })} min={1} max={256} />
            <FpNum label="Touch pts" value={fp.maxTouchPoints} onChange={(v) => setFp({ maxTouchPoints: v })} min={0} max={10} />
          </Stack>
        </Stack>
      </SectionCard>

      {/* WebGL */}
      <SectionCard title="WebGL" subtitle="Vendor / renderer">
        <Stack spacing={1.5}>
          <Fp label="Vendor" fp={fp} field="webglVendor" onChange={setFp} />
          <Fp label="Renderer" fp={fp} field="webglRenderer" onChange={setFp} />
        </Stack>
      </SectionCard>

      {/* Canvas & Audio */}
      <SectionCard title="Protection" subtitle="Noise & masking">
        <Stack spacing={1}>
          <Stack direction="row" spacing={2} sx={{ flexWrap: 'wrap', gap: 0.5 }}>
            <FormControlLabel
              control={<Switch checked={fp.canvasNoiseEnabled} onChange={(e) => setFp({ canvasNoiseEnabled: e.target.checked })} size="small" />}
              label="Canvas noise"
            />
            <FormControlLabel
              control={<Switch checked={fp.audioNoiseEnabled} onChange={(e) => setFp({ audioNoiseEnabled: e.target.checked })} size="small" />}
              label="Audio noise"
            />
            <FormControlLabel
              control={<Switch checked={fp.webRTCLeakProtect} onChange={(e) => setFp({ webRTCLeakProtect: e.target.checked })} size="small" />}
              label="WebRTC protect"
            />
          </Stack>
          <Stack direction="row" spacing={1.5}>
            <Fp label="Canvas seed" fp={fp} field="canvasNoiseSeed" onChange={setFp} type="number" />
            <Fp label="Audio seed" fp={fp} field="audioNoiseSeed" onChange={setFp} type="number" />
          </Stack>
        </Stack>
      </SectionCard>

      {/* Fonts */}
      <SectionCard title="Fonts" subtitle="Font masking">
        <Stack spacing={1}>
          <FormControlLabel
            control={<Switch checked={fp.fontFingerprintProtection} onChange={(e) => setFp({ fontFingerprintProtection: e.target.checked })} size="small" />}
            label="Font protection"
          />
          <TextField
            label="Custom fonts (per line)"
            size="small"
            fullWidth
            multiline
            minRows={2}
            value={(fp.customFonts ?? []).join('\n')}
            onChange={(e) =>
              setFp({ customFonts: e.target.value.split('\n').map((s) => s.trim()).filter(Boolean) })
            }
          />
        </Stack>
      </SectionCard>

      {/* Geolocation */}
      <SectionCard title="Geolocation" subtitle="Location">
        <Stack direction="row" spacing={1.5} sx={{ alignItems: 'center', flexWrap: 'wrap' }}>
          <FormControl size="small" sx={{ minWidth: 140 }}>
            <InputLabel>Mode</InputLabel>
            <Select
              label="Mode"
              value={fp.geolocation.mode}
              onChange={(e) => setFp({ geolocation: { ...fp.geolocation, mode: e.target.value as 'block' | 'spoof' } })}
            >
              <MenuItem value="block">Block</MenuItem>
              <MenuItem value="spoof">Spoof</MenuItem>
            </Select>
          </FormControl>
          {fp.geolocation.mode === 'spoof' && (
            <>
              <TextField
                label="Lat"
                type="number"
                size="small"
                value={String(fp.geolocation.latitude)}
                onChange={(e) => setFp({ geolocation: { ...fp.geolocation, latitude: Number(e.target.value) } })}
                sx={{ width: 110 }}
              />
              <TextField
                label="Lon"
                type="number"
                size="small"
                value={String(fp.geolocation.longitude)}
                onChange={(e) => setFp({ geolocation: { ...fp.geolocation, longitude: Number(e.target.value) } })}
                sx={{ width: 110 }}
              />
            </>
          )}
        </Stack>
      </SectionCard>

      {/* Privacy */}
      <SectionCard title="Privacy" subtitle="Flags">
        <Stack spacing={1}>
          <Stack direction="row" spacing={1.5} sx={{ flexWrap: 'wrap', gap: 0.5 }}>
            <FormControl size="small" sx={{ minWidth: 160 }}>
              <InputLabel>DNT</InputLabel>
              <Select
                label="DNT"
                value={fp.doNotTrack ?? 'null'}
                onChange={(e) => {
                  const v = e.target.value
                  setFp({ doNotTrack: v === 'null' ? null : v })
                }}
              >
                <MenuItem value="null">Off</MenuItem>
                <MenuItem value="1">On</MenuItem>
                <MenuItem value="0">Disabled</MenuItem>
              </Select>
            </FormControl>
            <FormControlLabel
              control={<Switch checked={fp.windowChromeSpoof} onChange={(e) => setFp({ windowChromeSpoof: e.target.checked })} size="small" />}
              label="window.chrome"
            />
            <FormControlLabel
              control={<Switch checked={fp.pluginsSpoof} onChange={(e) => setFp({ pluginsSpoof: e.target.checked })} size="small" />}
              label="Plugins spoof"
            />
          </Stack>
          <Alert severity="info" sx={{ borderRadius: 2, py: 0 }}>
            <Typography variant="caption">
              Seed: <code>{fp.seed}</code>
            </Typography>
          </Alert>
        </Stack>
      </SectionCard>

      <AutoGenerateDialog
        open={autoOpen}
        onClose={() => setAutoOpen(false)}
        onGenerated={(newFp) => {
          setFp(newFp)
          toast.success('Fingerprint generated')
        }}
      />

      {/* UA Suggest dialog */}
      <Dialog open={suggestOpen} onClose={() => setSuggestOpen(false)} fullWidth maxWidth="md">
        <DialogTitle>Suggest UA</DialogTitle>
        <DialogContent>
          <Stack direction="row" spacing={1} sx={{ mb: 1.5, flexWrap: 'wrap' }}>
            {['all', 'chrome', 'edge', 'brave', 'firefox'].map((b) => (
              <Button
                key={b}
                size="small"
                variant={uaFilter === b ? 'contained' : 'outlined'}
                onClick={() => setUaFilter(b)}
              >
                {b}
              </Button>
            ))}
          </Stack>
          <Typography variant="caption" color="text.secondary" sx={{ mb: 1, display: 'block' }}>
            Pick a real browser UA. Selecting one re-derives consistent values.
          </Typography>
          <List dense sx={{ maxHeight: 360, overflow: 'auto', border: '1px solid', borderColor: 'divider', borderRadius: 2 }}>
            {filteredUas.map((entry, i) => (
              <ListItemButton
                key={i}
                onClick={() => {
                  void (async () => {
                    try {
                      const derived = await window.stealth.deriveFingerprintFromUA(entry.ua, fp.seed)
                      setFp(derived)
                      setSuggestOpen(false)
                      toast.success(`Applied ${entry.browser} ${entry.version} (${entry.os})`)
                    } catch (e) {
                      toast.error(String(e))
                    }
                  })()
                }}
              >
                <ListItemText
                  primary={
                    <Typography component="span" sx={{ fontWeight: 600, fontSize: 12 }}>
                      {`${entry.browser} ${entry.version} · ${entry.os} · ${entry.device}`}
                    </Typography>
                  }
                  secondary={
                    <Typography component="span" sx={{ fontSize: 10, wordBreak: 'break-all', display: 'block' }} color="text.secondary">
                      {entry.ua}
                    </Typography>
                  }
                />
              </ListItemButton>
            ))}
            {filteredUas.length === 0 && (
              <Typography variant="body2" color="text.secondary" sx={{ p: 2, textAlign: 'center' }}>
                Loading...
              </Typography>
            )}
          </List>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setSuggestOpen(false)}>Close</Button>
        </DialogActions>
      </Dialog>
    </Box>
  )
}
