import { useEffect, useMemo, useState } from 'react'
import {
  Button,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  FormControl,
  InputLabel,
  MenuItem,
  Select,
  TextField,
  Typography
} from '@mui/material'
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome'
import type { BrowserType, DeviceType, TargetOS } from '@shared/types'
import { useToast } from '../hooks/useToasts'
import { BROWSER_LABELS } from '@shared/types'

const OS_OPTIONS: Array<{ value: TargetOS; label: string }> = [
  { value: 'windows', label: 'Windows 10 / 11' },
  { value: 'macos', label: 'macOS' },
  { value: 'linux', label: 'Linux' },
  { value: 'android', label: 'Android' },
  { value: 'ios', label: 'iOS' }
]

const DEVICE_OPTIONS: Array<{ value: DeviceType; label: string }> = [
  { value: 'desktop', label: 'Desktop' },
  { value: 'mobile', label: 'Mobile' }
]

const BROWSER_OPTIONS: Array<{ value: BrowserType; label: string }> = [
  { value: 'chrome', label: BROWSER_LABELS.chrome },
  { value: 'edge', label: BROWSER_LABELS.edge },
  { value: 'brave', label: BROWSER_LABELS.brave },
  { value: 'chromium', label: BROWSER_LABELS.chromium },
  { value: 'firefox', label: BROWSER_LABELS.firefox }
]

/**
 * "Auto-generate realistic fingerprint" dialog.
 * Picks device / OS / browser and produces a fully consistent fingerprint
 * via the main-process engine (seeded, reproducible).
 */
export function AutoGenerateDialog({
  open,
  onClose,
  onGenerated
}: {
  open: boolean
  onClose: () => void
  onGenerated: (fp: import('@shared/types').FingerprintConfig) => void
}): React.JSX.Element {
  const toast = useToast()
  const [device, setDevice] = useState<DeviceType>('desktop')
  const [os, setOs] = useState<TargetOS>(() => {
    // Renderer has no Node process; infer a sensible default from the UA.
    const ua = typeof navigator !== 'undefined' ? navigator.userAgent : ''
    if (/Mac OS X|Macintosh/.test(ua)) return 'macos'
    if (/Linux/.test(ua) && !/Android/.test(ua)) return 'linux'
    return 'windows'
  })
  const [browser, setBrowser] = useState<BrowserType>('chrome')
  const [ua, setUa] = useState('')
  const [busy, setBusy] = useState(false)

  // Reset state whenever the dialog reopens.
  useEffect(() => {
    if (open) {
      setUa('')
      setBusy(false)
    }
  }, [open])

  const generate = async (): Promise<void> => {
    setBusy(true)
    try {
      const fp = await window.stealth.generateFingerprint({
        device,
        os,
        browser,
        userAgent: ua.trim() || undefined
      })
      onGenerated(fp)
      toast.success('Fingerprint generated')
      onClose()
    } catch (e) {
      toast.error(String(e))
    } finally {
      setBusy(false)
    }
  }

  const mobileOnly = useMemo(() => device === 'mobile', [device])

  return (
    <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth>
      <DialogTitle sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
        <AutoAwesomeIcon color="primary" />
        Auto-generate realistic fingerprint
      </DialogTitle>
      <DialogContent>
        <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
          Generates a fully consistent fingerprint: UA, platform, screen, hardware, timezone,
          languages, WebGL GPU, fonts and noise seeds — all derived from one seeded generator.
        </Typography>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
          <FormControl fullWidth>
            <InputLabel>Device</InputLabel>
            <Select
              label="Device"
              value={device}
              onChange={(e) => setDevice(e.target.value as DeviceType)}
            >
              {DEVICE_OPTIONS.map((o) => (
                <MenuItem key={o.value} value={o.value}>
                  {o.label}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          <FormControl fullWidth>
            <InputLabel>OS</InputLabel>
            <Select label="OS" value={os} onChange={(e) => setOs(e.target.value as TargetOS)}>
              {OS_OPTIONS.map((o) => (
                <MenuItem key={o.value} value={o.value}>
                  {o.label}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          <FormControl fullWidth>
            <InputLabel>Browser</InputLabel>
            <Select label="Browser" value={browser} onChange={(e) => setBrowser(e.target.value as BrowserType)}>
              {BROWSER_OPTIONS.map((o) => (
                <MenuItem key={o.value} value={o.value}>
                  {o.label}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          <TextField
            label="Custom user-agent (optional)"
            placeholder="Mozilla/5.0 (Windows NT 10.0; Win64; x64) …"
            value={ua}
            onChange={(e) => setUa(e.target.value)}
            fullWidth
            helperText={mobileOnly ? 'Mobile UA strings include "Mobile".' : undefined}
          />
        </div>
      </DialogContent>
      <DialogActions sx={{ px: 3, pb: 2 }}>
        <Button onClick={onClose}>Cancel</Button>
        <Button variant="contained" disabled={busy} onClick={() => void generate()}>
          {busy ? 'Generating…' : 'Generate'}
        </Button>
      </DialogActions>
    </Dialog>
  )
}
